name: Sync Fork with Workflow Preservation

on:
  schedule:
    - cron: '0 0 * * *'  # Hàng ngày lúc 00:00 UTC
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Backup workflow file
        run: cp .github/workflows/sync.yml /tmp/sync-backup.yml

      - name: Add upstream repository
        run: |
          git remote add upstream https://github.com/Vencord/Installer.git
          git fetch upstream

      - name: Merge changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout main
          git merge --no-commit --no-ff --allow-unrelated-histories upstream/main
          
          # Khôi phục file workflow
          mkdir -p .github/workflows
          cp /tmp/sync-backup.yml .github/workflows/sync.yml
          git add .github/workflows/sync.yml

      - name: Commit changes
        run: |
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit"
          else
            git commit -m "Sync with upstream (preserved workflow)"
            git push origin main
          fi
